// Generated by https://quicktype.io

export interface IBrands {
    brands:  Brand[];
    success: boolean;
    message: string;
    status:  number;
}

export interface Brand {
    _id:  string;
    name: string;
    __v:  number;
}
