// Generated by https://quicktype.io

export interface ICollection {
    figures: Figure[];
    success: boolean;
    message: string;
    status:  number;
}

export interface Figure {
    _id:      string;
    name:     string;
    brand:    string;
    price:    number;
    quantity: number;
    thumbpath: string;
    
}
